//
// Created by Marley on 27/10/2023.
//

#ifndef DIARY_MANAGEMENT_PROJECT_COLOR_MANAGEMENT_H
#define DIARY_MANAGEMENT_PROJECT_COLOR_MANAGEMENT_H

void ErrorColor();

void NormalColor();

#endif //DIARY_MANAGEMENT_PROJECT_COLOR_MANAGEMENT_H
